Java interview questions and answers for beginner
numerica-ideas/community pull request #112
Opened 2023-09-09 14:52 UTC by kenany92

2023-09-17 22:18 UTC, danielkaiser80 requested changes
I like the overall ideas and maybe some of my remarks then would go to the advanced section, so let's discuss this, maybe.
Still, there are now interfaces with methods and so this part should be corrected.
Also, the best is, when a tool like Grammarly or LanguageTool (I prefer this) or Grazie in IntelliJ is also looking for language related issues.
Moreover, when I write that you should define JIT or OOP, you might just make a link to the respective question, maybe.

2023-09-17 22:18 UTC, danielkaiser80 commented on java/java-interview-questions-and-answers-beginner/README.md
> +  main() in Java is the entry point for any Java program. It is always written as **public static void main(String[] args)**.
some also write it as public static void main(String... args) and I had an interview where they asked for the reason and differences

2023-09-17 22:18 UTC, danielkaiser80 commented on java/java-interview-questions-and-answers-beginner/README.md
> +* ***String args[]***: It is the parameter passed to the main method.
Where does this come from and who does pass parameters. I mean, you do not call the main method in code.

2023-09-17 22:18 UTC, danielkaiser80 commented on java/java-interview-questions-and-answers-beginner/README.md
> +**17. What are different between constructors and methods**
"What is the difference / are the differences"

2023-09-17 22:18 UTC, danielkaiser80 commented on java/java-interview-questions-and-answers-beginner/README.md
> +  * *Final methods*: Method overriding is one of the important features of Java. But there are situations where we may not want to use this feature. To prevent a method from being overridden, we use
What about final static? (I mean it's all contained already but some interviewers like to confuse people)

2023-09-17 22:18 UTC, danielkaiser80 commented on java/java-interview-questions-and-answers-beginner/README.md
> +    class C extends A,B { //let's suppose it is possible
there is actually a way to do something like this with interfaces or mixing class and interface

interface A {
    default void sayHello() {
        System.out.println("Hello A!");
    }
}

interface B {
    default void sayHello() {
        System.out.println("Hello B!");
    }
}


    class C implements A, B {
        // This class can choose to override the sayHello method or use the default implementation.
        @Override
        public void sayHello() {
            A.super.sayHello();
        }
    }


But maybe this is extended stuff ;-)

2023-09-17 22:18 UTC, danielkaiser80 commented on java/java-interview-questions-and-answers-beginner/README.md
> +  However, "*Multiple Inheritance*" can be achieved by implementing multiple interfaces since interface forces the method overriding.
Ah here you have something with interfaces... maybe add my example?

2023-09-17 22:18 UTC, danielkaiser80 commented on java/java-interview-questions-and-answers-beginner/README.md
> +  An interface can only contain abstract methods whereas an abstract class can contain abstract and concrete methods. All methods in the interface must be public, but in the abstract class, except pr
This was changed, when default methods were introduced in interfaces

2023-09-17 22:18 UTC, danielkaiser80 commented on java/java-interview-questions-and-answers-beginner/README.md
> +  Compile-time polymorphism is also known as static polymorphism or early binding. Compile-time polymorphism is a polymorphism that is resolved during the compilation process. Overloading of methods
Java does not support operator overloading

2023-09-19 16:29 UTC, DDarkBC commented
Good job 😃  @kenany92 your article is really great, love it. Thanks also for contributing to the community. Together we're going to do great things and achieve big projects. 
OK, I've some improvments for you:

- [ ] What is Java?: You might want to mention that Java is also widely used for server-side development, Android apps, and much more.
- [ ] Features of Java: Consider breaking down the features into bullet points for easier readability.
- [ ] JDK, JRE, JVM: This section could be clearer if you use a table format.
- [ ] Heap and Stack Illustration: You mentioned an illustration, but there's no illustration provided.
- [ ] Static void main method: You could elaborate a bit more on why the main method is static and why it takes a String[] args parameter.
- [ ] Is empty .java file name a valid source file name?: This question is a bit unclear. Do you mean to ask if an empty Java file (i.e., a file with no content) is a valid source file?
- [ ] Wrapper Classes: You could provide examples of wrapper classes like Integer, Character, etc.
- [ ] Polymorphism: The example code for polymorphism is incorrect. In Java, you don't use implements for class inheritance; you use extends.
- [ ] Compile-Time and Run-Time Polymorphism: The code snippets have a typo; vois should be void.
- [ ] Exception: You could elaborate more on checked and unchecked exceptions.
- [ ] Automatic Garbage Collection: You might want to mention that the garbage collector is part of the Java Virtual Machine (JVM).
- [ ] Possible ways to making object eligible for garbage collection: The sentence "An island of isolation is a group of objects that reference each other but are not referenced by any active object in the application." could be confusing for beginners. Maybe provide a simpler explanation.

Also in a more General perspective : 
- [ ] Grammar and Spelling: There are some grammatical errors and typos throughout the article. Consider proofreading the article or using a grammar checker tool (Reverso for example).
- [ ] Code Formatting: Make sure that all code snippets are well-formatted. This will make it easier for the reader to understand the code.
- [ ] Consistency: Maintain consistency in the formatting, especially when you're listing points or explaining concepts.
- [ ] Examples: While you have provided examples in some sections, consider adding more practical examples to further illustrate your points (for next articles it'll be great).


Good Job Again Colleague!

2023-09-21 15:34 UTC, kenany92 commented on java/java-interview-questions-and-answers-beginner/README.md
> +  main() in Java is the entry point for any Java program. It is always written as **public static void main(String[] args)**.
You are right. But didn't want to talk about different ways to write the main method. That could be a topic for an article. Keep in mind that It is for beginners.

2023-09-21 15:39 UTC, kenany92 commented on java/java-interview-questions-and-answers-beginner/README.md
> +* ***String args[]***: It is the parameter passed to the main method.
Same as above. I wouldn't provide a deep explanation of the main method. However, I could update It and put the brackets in the same way as in the introduction to avoid confusion.

2023-09-21 15:50 UTC, kenany92 commented on java/java-interview-questions-and-answers-beginner/README.md
> +    Java is a simple programming language and easy to understand because it does not contain complexities that exist in prior programming languages. Simplicity was the design aim of Javasoft people b
Javasoft is for Sun Microsystems when the language was created

https://www.infoworld.com/article/2077131/javasoft-wrestles-with-success.html
http://www.columbia.edu/cu/help/jdk/docs/relnotes/contacts.html

2023-09-21 16:50 UTC, kenany92 commented
@DDarkBC did you follow this link to see what the article looks for?
https://github.com/kenany92/community/tree/java-interview-questions-and-answers-beginner/java/java-interview-questions-and-answers-beginner

2023-09-28 09:36 UTC, dassiorleando commented
@kenany92 please is that OK, do you need another round of review?

2023-12-25 21:44 UTC, dassiorleando commented
@kenany92 please is it possible to check the items you have done which are pointed out by @DDarkBC in the list on the top?

2023-12-27 13:48 UTC, danielkaiser80 reviewed
I see just two little language issues, in my opinion, these would be nice to fix but not 100% necessary.
Then of course we might want to discuss the list above by @DDarkBC as it feels to me that he sees the scope of the article differently from @kenany92 and me

2023-12-27 13:48 UTC, danielkaiser80 commented on java/java-interview-questions-and-answers-beginner/README.md
> +* Advanced developer: We all know that our brain is sometimes not reliable in memorizing, so It is not strange to forget about something you learned a long time ago. You can find here a memory remind
I just see that you capitalized "It" in the phrase "It is", should be "it is".

2023-12-27 13:48 UTC, danielkaiser80 commented on java/java-interview-questions-and-answers-beginner/README.md
> +  * At the compilation: When your program calls a method that could throw a certain type of exception, Java will prevent a successful compilation until you handle that exception or specify that the c
It should be "at compilation" and "at runtime" respectively.

2023-12-29 14:18 UTC, danielkaiser80 approved these changes

2023-12-31 00:38 UTC, dassiorleando approved these changes

2023-12-31 13:22 UTC, DDarkBC commented
It's good for me 👌🏾

2023-12-31 13:26 UTC, DDarkBC approved these changes

2023-12-31 18:58 UTC, merged

2023-12-31 18:59 UTC, dassiorleando commented
Me move live with this then, thank you so much for your ALWAYS valuable contributions.
🥇 🚀 💯 👍