Demystifying Terraform Modules
numerica-ideas/community pull request #117
Opened 2023-09-25 15:23 UTC by kemanedonfack

2023-10-02 14:38 UTC, dassiorleando requested changes
@kemanedonfack could you please take a look at the following points before we push the article live?

Great article 👍

2023-10-02 14:38 UTC, dassiorleando commented on terraform/terraform-module/README.md
> +Our EC2 instance module exposes the instance ID as an output in `outputs.tf`:
The output is the instance public IP instead, so the description on the top should match.

2023-10-02 14:38 UTC, dassiorleando commented on terraform/terraform-module/README.md
> +## Using the Module
Plural form: **Using the Modules**

2023-10-02 14:38 UTC, dassiorleando commented on terraform/terraform-module/README.md
> +
Let's add the source code link after the article content:

The complete source code of the project is available on [GitHub](https://github.com/numerica-ideas/community/tree/master/terraform/terraform-module).

2023-10-02 14:38 UTC, dassiorleando commented on terraform/terraform-module/README.md
> +
Before the Discord block here, could we add a call-to-action to another Terraform article?

Example: 

In order to better your DevOps skills, learn [How To Deploy WordPress on a 2-Tier AWS Architecture using Terraform](https://blog.numericaideas.com/deploy-wordpress-2-tier-aws-architecture-with-terraform) by following this practical workshop:

[![FeaturedImage](../deploy-wordpress-2tier-aws-architecture-with-terraform/images/Deploying-WordPress-on-a-2-Tier-AWS-Architecture-with-Terraform.png)](https://blog.numericaideas.com/deploy-wordpress-2-tier-aws-architecture-with-terraform)

2023-10-02 14:38 UTC, dassiorleando commented on terraform/terraform-module/README.md
> +# Demystifying Terraform Modules: A Comprehensive Guide&nbsp;[![Hits](https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fgithub.com%2Fnumerica-ideas%2Fcommunity%2Ftree%2Fmaster%2F
What about keeping the title as simple as: **Demystifying Terraform Modules**

Without the comprehnsive statement!

2023-10-02 14:40 UTC, dassiorleando commented
Also, let's add this before the **Prerequisites** section:

> The **YouTube Channels** in both English (En) and French (Fr) are now accessible, feel free to subscribe by clicking [here](https://www.youtube.com/@numericaideas/channels?sub_confirmation=1).

2023-10-02 15:22 UTC, dassiorleando commented on terraform/terraform-module/README.md
> +
This link is incorrect in the recent changes, it should go to **numerica-ideas** repo, not to your fork.

2023-10-02 15:23 UTC, dassiorleando commented on terraform/terraform-module/README.md
> +
You changed the article link for the image, it should match with the article link on the blog ... not the repo code of your fork.

2023-10-02 15:27 UTC, kemanedonfack commented on terraform/terraform-module/README.md
> +
I put a relative link

<img width="547" alt="terraform module" src="https://github.com/numerica-ideas/community/assets/70517765/29328119-3058-44f6-9b2d-8cb61c1be675">

2023-10-02 19:55 UTC, dassiorleando requested changes
More review comments are coming your way @kemanedonfack
I hope these will help make this piece of content even better.

2023-10-02 19:55 UTC, dassiorleando commented on terraform/terraform-module/README.md
> +The complete source code of the project is available on [GitHub](/terraform/terraform-module/).
Let's use an absolute link here for the source code link, that way it'll be easier when migrating content.

2023-10-02 19:55 UTC, dassiorleando commented on terraform/terraform-module/README.md
> +![FeaturedImage](../deploy-wordpress-2tier-aws-architecture-with-terraform/images/Deploying-WordPress-on-a-2-Tier-AWS-Architecture-with-Terraform.png)
The targetted link of this image_link should be: https://blog.numericaideas.com/deploy-wordpress-2-tier-aws-architecture-with-terraform

2023-10-02 19:55 UTC, dassiorleando commented on terraform/terraform-module/README.md
> +## How to Create Terraform Modules
Sorry, I misguided you here, we should have the question mark at the end.

**How to Create Terraform Modules?**

2023-10-02 19:55 UTC, dassiorleando commented on terraform/terraform-module/README.md
> +- **Versioning**: Modules can be versioned, ensuring consistent configurations throughout your infrastructure.
I do believe that we should add a sub-section here that talks about the **Terraform Registry** as a way to reuse other public modules created by the community and that it's a trusted source managed by **Hashicorp**.

Hint: https://blog.numericaideas.com/introduction-to-terraform#provider

2023-10-02 19:55 UTC, dassiorleando commented on terraform/terraform-module/README.md
> +In this example, we use a module named **example** located in the `./modules/my-module` directory. We also provide a value for the `instance_count` variable.
In this section, could you give some info about how we could have **reused/installed** that module if it was stored in the **Terraform Registry** or located in a **GitHub repository**?

Simply knowing the possibilities is great, even if the practical example won't cover these cases.

2023-10-02 20:42 UTC, dassiorleando commented on terraform/terraform-module/README.md
> +
Here's the featured image to use for the article, just before the YouTube call-to-action message:

![Terraform Modules](https://github.com/numerica-ideas/community/assets/7150752/01225dc2-f969-46de-8ebc-522c0710d95c)

Another example: https://github.com/kemanedonfack/community/tree/terraform/terraform/deploy-wordpress-2tier-aws-architecture-with-terraform

2023-10-02 20:53 UTC, kemanedonfack commented on terraform/terraform-module/README.md
> +
Nice

2023-10-03 02:21 UTC, dassiorleando commented on terraform/terraform-module/README.md
> +![FeaturedImage](../deploy-wordpress-2tier-aws-architecture-with-terraform/images/Deploying-WordPress-on-a-2-Tier-AWS-Architecture-with-Terraform.png)
> The targetted link of this image_link should be: https://blog.numericaideas.com/deploy-wordpress-2-tier-aws-architecture-with-terraform

[Still not done]

2023-10-03 02:25 UTC, merged