completed article on -maven for beginners-
numerica-ideas/community pull request #134
Opened 2024-01-16 15:53 UTC by ajimbong

I just completed the article on Maven for beginners. I'd appreciate it if my work could be reviewed for possible changes or merged.

2024-01-20 02:06 UTC, dassiorleando requested changes
@ajimbong This is a great article, I enjoyed reading it.

I left a few comments that may improve its quality, I hope so.

Do let me know what your thoughts are.

Thanks.

2024-01-20 02:06 UTC, dassiorleando commented on java/maven-for-beginners/README.md
> +`exec:java` is what calls our plugin.
... is what runs our project?

2024-01-20 02:06 UTC, dassiorleando commented on java/maven-for-beginners/README.md
> +In this article, we went over what Maven is about and saw some of its commands for compiling and packaging projects, etc. We also how to manage dependencies and plugins with Maven all working on a fu
... We also **"explained"** how to manage dependencies ... with Maven **"while working on a little fun"** project.
I hope you learned **"something new"** ...

2024-01-20 02:08 UTC, dassiorleando commented
@ajimbong another comment, could you put the final source code in the same folder as well?
Here's an example: https://github.com/ajimbong/numerica-ideas-community/tree/post/ajim/nodejs/node-support-env-files

2024-01-21 15:46 UTC, ajimbong commented on java/maven-for-beginners/README.md
> +mavn -v
That's what I meant, it was a typo. Let me correct it.

2024-01-21 16:10 UTC, ajimbong commented on java/maven-for-beginners/README.md
> +After running it, you will be prompted to provide some values. You can just provide the `groupId:` and `artifactId:`, and leave the rest as default. Once your project has been created, navigate to th
Ohh I see. I thought that had always been the case.

I'm relatively very new to Java, it's just been a couple of months since I started using the language. But I'll do well to research on that and see how to fit it in the article.

2024-01-21 16:56 UTC, ajimbong commented on java/maven-for-beginners/README.md
> +After running it, you will be prompted to provide some values. You can just provide the `groupId:` and `artifactId:`, and leave the rest as default. Once your project has been created, navigate to th
I have done some research, and most of the resources I came across mentioned that it isn't mandatory for the *groupId* and *package name* to be the same. Like this issue on StackOverflow: https://stackoverflow.com/questions/59206147/whats-the-difference-between-package-and-groupid-in-maven

However, it's important for the *package* to be unique so it wouldn't clash with other packages, hence a good reason to use the value of the *groupId*. I know you didn't say *mandatory*, but that's the impression I got when reading your comment.

I am still going to mention it in the article though.

2024-01-21 17:18 UTC, ajimbong commented on java/maven-for-beginners/README.md
> +After running it, you will be prompted to provide some values. You can just provide the `groupId:` and `artifactId:`, and leave the rest as default. Once your project has been created, navigate to th
> As a best practice, it's important for the default **package name** to have the same value as the **groupId**, to maintain a consistent project structure and avoid conflicts in package names. And that's how Maven sets it up by default.

Please what do you think about this?

2024-01-21 18:15 UTC, ajimbong commented on java/maven-for-beginners/README.md
> +Before we compile or package our project, we need to first understand Maven's lifecycle and its commands. Maven has 8 lifecycle commands, and they are: Validate, Compile, Test, Package, Integration T
I'm not entirely sure what that is about. But this is a section of the docs that goes into the build LifeCycle:

https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#build-lifecycle-basics

And it is different.

2024-01-21 18:20 UTC, ajimbong commented on java/maven-for-beginners/README.md
> +- `verify` : Verifies all checks and tests pass.
sure! I guess I'll go with the descriptions provided by the official docs:

`verify` - run any checks on the results of integration tests to ensure quality criteria are met.

2024-01-21 19:03 UTC, ajimbong commented on java/maven-for-beginners/README.md
> +mvn archetype:generate -Dfilter=org.apache.maven.archetypes:
`mvn archetype:generate`: Is the command we use to create a new maven project based on an archetype.

 Then the `-Dfilter=org.apache.maven.archetypes:` flag will only get the archetypes available in org.apache.maven.archetypes package, where we'll have to select the particular archetype we want through the interactive prompt. By default, it selects the `maven-archetype-quickstart` archetype for us.

Other examples of archetypes available in this package are:
- maven-archetype-webapp
- maven-archetype-plugin
- maven-archetype-simple

etc

2024-01-21 20:03 UTC, ajimbong commented on java/maven-for-beginners/README.md
> +
You're right, I think I should add a definition for that.

2024-01-21 20:36 UTC, ajimbong commented on java/maven-for-beginners/README.md
> +
>Dependencies are external pieces of code, or libraries we use in projects to perform specific tasks with ease. Maven offers a streamlined way of working with dependencies where we don't have to go out and download external libraries and manually import them into our project. We only tell Maven what dependencies we need, and it handles the rest, fetching the dependencies and making them available in the project.

This is a definition I came up with.

2024-01-23 01:42 UTC, dassiorleando commented on java/maven-for-beginners/README.md
> +Before we compile or package our project, we need to first understand Maven's lifecycle and its commands. Maven has 8 lifecycle commands, and they are: Validate, Compile, Test, Package, Integration T
Maven have more than that according to the link I shared on the top, could we rephrase it like: "The default Maven lifecycle has 8 major phases"?

2024-01-23 01:46 UTC, dassiorleando commented on java/maven-for-beginners/README.md
> +
Excellent definition, I like it 💯

2024-01-23 01:54 UTC, dassiorleando commented on java/maven-for-beginners/README.md
> +
The explanation is good, but I would suggests to change the examples since JCenter is deprecated and the other link is not found:
- [JFrog](https://jfrog.com/artifactory/)
- [AWS CodeArtifact](https://aws.amazon.com/codeartifact/)
- [JitPack](https://jitpack.io/)

2024-01-23 01:59 UTC, dassiorleando requested changes
@ajimbong only two items remain, and we are good to do.

- https://github.com/numerica-ideas/community/pull/134#discussion_r1462630422
- https://github.com/numerica-ideas/community/pull/134#discussion_r1462638522

Again, great updates.

2024-01-23 01:59 UTC, dassiorleando commented on java/maven-for-beginners/README.md
> +> This dependency is fetched from the [Maven central repository](https://mvnrepository.com/artifact/com.github.ricksbrown/cowsay), which is the default, publicly available repository for getting Mave
The explanation is good, but I would suggests to change the examples since JCenter is deprecated and the other link is not found:
- [JFrog](https://jfrog.com/artifactory/)
- [AWS CodeArtifact](https://aws.amazon.com/codeartifact/)
- [JitPack](https://jitpack.io/)

2024-01-23 20:21 UTC, ajimbong commented on java/maven-for-beginners/README.md
> +Before we compile or package our project, we need to first understand Maven's lifecycle and its commands. Maven has 8 lifecycle commands, and they are: Validate, Compile, Test, Package, Integration T
Alright, sure.

2024-01-23 21:02 UTC, ajimbong commented on java/maven-for-beginners/README.md
> +> This dependency is fetched from the [Maven central repository](https://mvnrepository.com/artifact/com.github.ricksbrown/cowsay), which is the default, publicly available repository for getting Mave
Thank you for the corrections.

I have gone ahead and made the necessary adjustments.

2024-01-25 13:16 UTC, dassiorleando commented on java/maven-for-beginners/README.md
> +Before we compile or package our project, we need to first understand Maven's lifecycle and its commands. Maven has 8 lifecycle commands, and they are: Validate, Compile, Test, Package, Integration T
Nice improvement.

2024-01-25 13:17 UTC, dassiorleando commented on java/maven-for-beginners/README.md
> +> This dependency is fetched from the [Maven central repository](https://mvnrepository.com/artifact/com.github.ricksbrown/cowsay), which is the default, publicly available repository for getting Mave
I have seen the changes, everything is alright ... Thank you.

2024-01-25 13:18 UTC, dassiorleando approved these changes
@ajimbong great work on this first article, it's scheduled to be published on Saturday or Tuesday.

Thanks for the hard work.

2024-01-25 13:19 UTC, dassiorleando commented
@ajimbong Meanwhile, could you fix the existing conflicts in it, please?

2024-01-28 17:28 UTC, dassiorleando requested changes
Conflicts to fix.

2024-01-28 17:30 UTC, dassiorleando approved these changes

2024-01-28 17:31 UTC, merged