Add the Design pattern article
numerica-ideas/community pull request #139
Opened 2024-02-20 14:17 UTC by elmansour1

2024-02-26 12:16 UTC, dassiorleando requested changes
@elmansour1 this is a great content, all the terms are nicely explained, but we can slightly improve the quality of the article before releasing it.

Thanks in advance to consider the above-mentioned points.

Looking forward to your updates.

Cheers!

2024-02-26 12:16 UTC, dassiorleando commented on architecture/design-pattern/README.md
> +![fearuredImage](./Images/design-pattern.png)
You have a **"duplicated featured image"** in your files, and the quality of the one you used could be improved.

For the featured images, we use visually appealing ones like the previous images published on the blog.
https://numericaideas.com/blog/

I can provide it to you if you can't do something similar.

2024-02-26 12:32 UTC, elmansour1 commented on architecture/design-pattern/README.md
> +## Classification of design patterns
ok

2024-02-26 12:37 UTC, elmansour1 commented on architecture/design-pattern/README.md
> +![fearuredImage](./Images/design-pattern.png)
Yes, can you provide it to me please ?

2024-02-26 12:51 UTC, dassiorleando commented on architecture/design-pattern/README.md
> +#### Singleton:
> i remove the ":" at the end of each title ?

Yes let's remove them and make sure each pattern has a full tile like **"Singleton Design Pattern"** ... not only ~~"Singleton"~~.

2024-02-26 12:56 UTC, elmansour1 commented on architecture/design-pattern/README.md
> +#### Singleton:
I think it's already ok here

2024-02-27 03:12 UTC, dassiorleando requested changes

2024-02-27 03:12 UTC, dassiorleando commented on architecture/design-pattern/README.md
> +---
Could we remove this section and use the following:

# Design Patterns&nbsp;[![Hits](https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fgithub.com%2Fnumerica-ideas%2Fcommunity%2Ftree%2Fmaster%2Farchitecture%2Fdesign-patterns&count_bg=%2379C83D&title_bg=%23555555&icon=&icon_color=%23E7E7E7&title=hits&edge_flat=false)](https://numericaideas.com/blog/design-patterns)

**This article was originally written by "Faouziel Mansour" on the blog**: https://numericaideas.com/blog/design-patterns


It's almost the same for other articles, here's an example: https://github.com/numerica-ideas/community/edit/master/java/maven-for-beginners/README.md

2024-02-27 03:12 UTC, dassiorleando commented on architecture/design-pattern/README.md
> +![fearuredImage](./Images/design-pattern.png)
@elmansour1 I still see the duplicated featured images in the images folder.

TODO:
- The images folder should be named **images**, not Images. small caps.
- The article folder should be named **design-patterns**, not design-pattern. plural form.

As attached file, the featured image to use:

![Design Patterns](https://github.com/numerica-ideas/community/assets/7150752/bded2367-64af-4e70-98bd-27c38470b426)

2024-02-27 03:12 UTC, dassiorleando commented on architecture/design-pattern/README.md
> +## Why Design Patterns?
I'm not sure if it's good to put the **"Why Design Patterns"** part after we have listed them on the top.
What do you think about moving it after the **"Historical"** section?

2024-02-27 03:12 UTC, dassiorleando commented on architecture/design-pattern/README.md
> +
This text should go before the conclusion:

———————

We have just started our journey to build a network of professionals to grow even more our free knowledge-sharing community that’ll give you a chance to learn interesting things about topics like cloud computing, software development, and software architectures while keeping the door open to more opportunities.

Does this speak to you? If **YES**, feel free to [Join our Discord Server](https://discord.numericaideas.com) to stay in touch with the community and be part of independently organized events.

———————

This one after the conclusion:

Thanks for reading this article. Like, recommend, and share if you enjoyed it. Follow us on [Facebook](https://www.facebook.com/numericaideas), [Twitter](https://twitter.com/numericaideas), and [LinkedIn](https://www.linkedin.com/company/numericaideas) for more content.


Here's an existing example: https://github.com/numerica-ideas/community/edit/master/java/maven-for-beginners/README.md

2024-02-27 05:16 UTC, elmansour1 commented on architecture/design-pattern/README.md
> +---
ok

2024-02-27 05:17 UTC, elmansour1 commented on architecture/design-pattern/README.md
> +## Why Design Patterns?
Ah yeah. it's ok. i move after historical section

2024-02-27 05:31 UTC, elmansour1 commented on architecture/design-pattern/README.md
> +
ok

2024-02-27 11:23 UTC, dassiorleando approved these changes
@elmansour1 great article, I'm merging it now.
Thanks for the hard work delivering this.

2024-02-27 11:24 UTC, merged