push the implementation of design pattern observer
numerica-ideas/community pull request #147
Opened 2024-05-25 13:08 UTC by elmansour1

2024-06-11 10:56 UTC, dassiorleando requested changes
Great README file, I like it ... thanks for doing this.
I just left small improvements to review @elmansour1.
Thanks for the hard work.

2024-06-11 10:56 UTC, dassiorleando commented on java/design-pattern-observer/src/com/faelma/pattern/observer/ObserverMain.java
> +		eleve.ajouterNote(5.0f);
Could we change this to student. addGrades(5.0f); ?
I made the related change to the article already.
Thanks.

2024-06-11 10:56 UTC, dassiorleando commented on java/design-pattern-observer/src/com/faelma/pattern/observer/ObserverMain.java
> +		eleve.ajouterNote(13.0f);
Same here.

2024-06-11 10:56 UTC, dassiorleando commented on java/design-pattern-observer/README.md
> +The case study, we will take as an example is a small application that manages notes to illustrate the implementation of the observer pattern in Java. The diagram below presents the architecture of t
Let's change notes to **grades**.

2024-06-11 10:56 UTC, dassiorleando commented on java/design-pattern-observer/README.md
> +3. ConcreteObserver: NotesObserver.
This should be the **GradesObserver** class.

2024-06-11 10:56 UTC, dassiorleando commented on java/design-pattern-observer/README.md
> +[![FeaturedImage](./images/architecture.png)](https://numericaideas.com/blog/design-pattern-observer)
Could you use the same diagram you improved and uploaded into the article?
The one that use **Grades** instead of Notes.

https://assets.numericaideas.com/2024/06/appli-note-pattern-observer1.png

2024-06-11 11:09 UTC, elmansour1 reviewed
it's done

2024-06-13 02:56 UTC, dassiorleando approved these changes
Great changes, Thank you @elmansour1

2024-06-13 02:57 UTC, merged