migrate wordpress site from cpanel to aws
numerica-ideas/community pull request #150
Opened 2024-09-05 06:57 UTC by ngoussong

2024-09-05 06:58 UTC, ngoussong commented
This is my first commit and I'm waiting for feedback :)

2024-09-05 07:05 UTC, ngoussong commented
Have some questions about placing screenshots in the article

2024-09-09 12:07 UTC, dassiorleando requested changes
Hello @ngoussong, thank you for your effort into producing this nice article.
I just left a few comments for improvements so that it meet other criteria to make it even more accessible to the public.
Thanks.

2024-09-09 12:07 UTC, dassiorleando commented on aws/migrate-wordpress-site-from-cpanel-to-aws/README.md
> +•	Access to your current WordPress site via cPanel.
- The list could use the simple bullet formatting with dash instead of dot, like this actual comment.
- I believe we should have a main section for the practical demo with a title (#) similar to "Migrating WordPress from Cpanel to AWS", then other sections could be subsections (##).

2024-09-09 12:07 UTC, dassiorleando commented on aws/migrate-wordpress-site-from-cpanel-to-aws/README.md
> +# Final Tips
I would recommend putting the **Final Tips** before the **Conclusion**, generally the conclusion mark the very end.

2024-09-09 12:07 UTC, dassiorleando commented on aws/migrate-wordpress-site-from-cpanel-to-aws/README.md
> +# Step 1: Backup Your WordPress Site
What do you think about improving all the practical sections to be as intuitive as possible?
For tech content, we always go step by step as you did, it's good, but in addition we provide screenshots of each step, with the UI where we clicked so that anyone will be able to follow-along and reproduce it with the same level of precision.

2024-09-30 11:46 UTC, dassiorleando requested changes
@ngoussong great addition so far, thank you for the extended efforts.
Could you take a look at the last comments please?

2024-09-30 11:46 UTC, dassiorleando commented on aws/migrate-wordpress-site-from-cpanel-to-aws/README.md
> +-	Make the website secure => sudo /opt/bitnami/bncert-tool
Make the website secure: could you explain this section more please?
What it does.

2024-09-30 11:46 UTC, dassiorleando commented on aws/migrate-wordpress-site-from-cpanel-to-aws/README.md
> +-	Use an SCP client or FTP to upload your WordPress files (from the backup) to the /htdocs/ directory on your EC2 instance.
The migration process could be even clearer, what CLI command or FTP options did we use to be able to migrate from our local computer to the server?

2024-09-30 11:46 UTC, dassiorleando commented on aws/migrate-wordpress-site-from-cpanel-to-aws/README.md
> +-	You can use Let's Encrypt to install a free SSL certificate on your site. Bitnami provides an automated tool for this purpose.
Is it also an option to use **"AWS ACM"** to create a free public SSL certificate for our domain? If yes, I would recommend adding it as a second bullet.

2024-10-03 00:08 UTC, merged