Provided a solution using Python 3 to phone number letters combinations algorithm.
numerica-ideas/community pull request #38
Opened 2023-04-08 12:07 UTC by yvantcheuffa

- Provided a solution using Python 3 to phone number letters combinations algorithm.
- Added link to the solution in README.md file.

2023-04-08 12:49 UTC, dassiorleando commented
Good thing @yvantcheuffa, Thank you.

Everything is alright for me but just to keep things centralized, could you consider the following?

- Instead of having two lines for the same challenge in the readme, we can use the first one and describe both solutions in the same file.
- Update the phone readme to highlight the first solution with its runtime (45ms), description and code and the second solution with your runtime (38 ms), description and code as well.
- The by line could have two names: foka and you.

What’s your take on that?

2023-04-08 17:20 UTC, yvantcheuffa commented
> Good thing @yvantcheuffa, Thank you.
> 
> Everything is alright for me but just to keep things centralized, could you consider the following?
> 
> * Instead of having two lines for the same challenge in the parent readme, we can use the existing one and describe both solutions in the same child readme.
> * Update the phone readme(letter-combinations-phone-number.md) to highlight the first solution with its runtime (45ms), description and code and the second solution with your runtime (38 ms), description and code as well.
> * The “by line” could have two names: foka and you.
> 
> What’s your take on that?



> Good thing @yvantcheuffa, Thank you.
> 
> Everything is alright for me but just to keep things centralized, could you consider the following?
> 
> * Instead of having two lines for the same challenge in the parent readme, we can use the existing one and describe both solutions in the same child readme.
> * Update the phone readme(letter-combinations-phone-number.md) to highlight the first solution with its runtime (45ms), description and code and the second solution with your runtime (38 ms), description and code as well.
> * The “by line” could have two names: foka and you.
> 
> What’s your take on that?

I understand your point. Let me update this PR.

2023-04-08 21:41 UTC, messaismael commented
@yvantcheuffa can you remove this file cause it's a duplication?

`letter-combinations-of-a-phone-number.md`

2023-04-08 21:51 UTC, messaismael requested changes
Can you remove this file also it's a duplication.

`letter-combinations-of-a-phone-number.md`

2023-04-08 21:51 UTC, messaismael commented on algorithms/letter-combinations-phone-number.md
> +Next, we create an empty list that will serve as an accumulator and another list for matches containing strings who values are the equivalent
... strings `whose` values ...

2023-04-08 21:51 UTC, messaismael commented on algorithms/letter-combinations-phone-number.md
> +**Solution 1 (using JavaScript)**:
The solution is in `TypeScript` rather

2023-04-09 14:33 UTC, yvantcheuffa commented on algorithms/letter-combinations-phone-number.md
> +**Solution 1 (using JavaScript)**:
@messaismael Done !

2023-04-09 20:33 UTC, dassiorleando approved these changes

2023-04-09 20:36 UTC, merged

2023-04-09 20:36 UTC, dassiorleando commented
PR merged, thanks for the efforts guys.