Difference between Behaviorsubject, Subject, and Observable in RxJS
numerica-ideas/community pull request #44
Opened 2023-04-28 16:56 UTC by messaismael

2023-04-30 22:13 UTC, dassiorleando requested changes

2023-04-30 22:13 UTC, dassiorleando commented on web/difference-between-behaviorsubject-subject-observable-in-rxjs/README.md
Sorry, but I don't understand this sentence: With Subject, It can have many producers and a producer runs only once for all observers.

2023-04-30 22:13 UTC, dassiorleando commented on web/difference-between-behaviorsubject-subject-observable-in-rxjs/README.md
Another small suggestion if you are ok with that:

**BehaviorSubject** also ensures the last published event is consumed by **new** consumers.

2023-04-30 22:13 UTC, dassiorleando commented on web/difference-between-behaviorsubject-subject-observable-in-rxjs/README.md
The title of the **BehaviorSubject** should have an uppercase S.

2023-04-30 22:13 UTC, dassiorleando commented on web/difference-between-behaviorsubject-subject-observable-in-rxjs/README.md
The BehaviorSubject example doesn't use the **subscribe** and neither the **next** function.

2023-04-30 22:13 UTC, dassiorleando commented on web/difference-between-behaviorsubject-subject-observable-in-rxjs/README.md
**Conclusion**:

In conclusion, we hope that this article has cleared up any confusion surrounding Observable, Subject, and BehaviorSubject. If you have any further thoughts or insights to add, please do not hesitate to share them with us. We welcome all feedback and suggestions.

2023-05-07 03:59 UTC, dassiorleando commented on web/difference-between-behaviorsubject-subject-observable-in-rxjs/README.md
> Reactive **Extensions** for JavaScript

Not fixed

2023-05-07 04:10 UTC, dassiorleando requested changes

2023-05-07 04:10 UTC, dassiorleando commented on web/difference-between-observable-subject-behaviorsubject-in-rxjs/README.md
> +A **Subject**’s a kind of observable that allows unlike a simple observable, the ability to publish an event after subscription, but it has no initial value. In addition to the `subscribe()` method,
@messaismael I still don't understand this, could you explain it, please?

From my understanding, a Subject has **one** producer and **many** listeners/observers.

2023-05-07 04:11 UTC, dassiorleando commented on web/difference-between-observable-subject-behaviorsubject-in-rxjs/README.md
> +A **Subject**’s a kind of observable that allows unlike a simple observable, the ability to publish an event after subscription, but it has no initial value. In addition to the `subscribe()` method,
Do you mean "Reactive Extensions for JavaScript" instead of "Reactive Extension for JavaScript"?

2023-05-07 08:32 UTC, messaismael commented on web/difference-between-observable-subject-behaviorsubject-in-rxjs/README.md
> +A **Subject**’s a kind of observable that allows unlike a simple observable, the ability to publish an event after subscription, but it has no initial value. In addition to the `subscribe()` method,
It's ok now

2023-05-07 14:16 UTC, dassiorleando commented on web/difference-between-observable-subject-behaviorsubject-in-rxjs/README.md
> +A **Subject**’s a kind of observable that allows unlike a simple observable, the ability to publish an event after subscription, but it has no initial value. In addition to the `subscribe()` method,
@messaismael my comments still apply.

1) You still say a Subject can have many producers? Is that possible?

Could you point me to any example and/or documentation in case I'm missing something?

2) It's "Reactive Extension for JavaScript", **JavaScript** always has a capital S.

3) **BehaviorSubject** always has a capital S, in the title.

Do let me know when it's correct, Thanks.

2023-05-07 14:17 UTC, dassiorleando requested changes
The previous review still applies.

2023-05-09 00:53 UTC, dassiorleando commented on web/difference-between-observable-subject-behaviorsubject-in-rxjs/README.md
> +A **Subject**’s a kind of observable that allows unlike a simple observable, the ability to publish an event after subscription, but it has no initial value. In addition to the `subscribe()` method,
@messaismael could you take a look at this comment, please?

2023-05-14 15:33 UTC, dassiorleando commented
@messaismael anything new on this thread?

2023-05-16 06:52 UTC, messaismael commented on web/difference-between-observable-subject-behaviorsubject-in-rxjs/README.md
> +A **Subject**’s a kind of observable that allows unlike a simple observable, the ability to publish an event after subscription, but it has no initial value. In addition to the `subscribe()` method,
Ppoint 1 was a mistake

2023-05-16 06:53 UTC, messaismael commented on web/difference-between-observable-subject-behaviorsubject-in-rxjs/README.md
> +A **Subject**’s a kind of observable that allows unlike a simple observable, the ability to publish an event after subscription, but it has no initial value. In addition to the `subscribe()` method,
The points 3, 2 and 1 are 🆗  now

2023-05-22 01:48 UTC, dassiorleando commented on web/difference-between-observable-subject-behaviorsubject-in-rxjs/README.md
> +A **Subject**’s a kind of observable that allows unlike a simple observable, the ability to publish an event after subscription, but it has no initial value. In addition to the `subscribe()` method,
Good thing, Thank you for your commitment to this.
I merge it now.

2023-05-22 01:49 UTC, merged