Microservices App Deployment to kubernetes with Helm via GitLab CI
numerica-ideas/community pull request #49
Opened 2023-05-01 12:38 UTC by kemanedonfack

2023-05-07 04:44 UTC, dassiorleando requested changes

2023-05-07 04:44 UTC, dassiorleando commented on kubernetes/spring-microservice-deployment-gitlab-helm/.idea/.gitignore
> +# Default ignored files
Could we hide entirely the folder **.idea** from within the project .gitignore file?
Right now it shows that your PR has +400 files changed which is a bit scary :)

2023-05-07 04:44 UTC, dassiorleando commented on kubernetes/spring-microservice-deployment-gitlab-helm/.gitlab-ci.yml
> +    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
I'm still concerned about this, won't it print the **Docker password** into the logs?

If Yes, could we remove it, please? Else it'll be great if you clarify what I'm missing, Thank you.

2023-05-07 04:44 UTC, dassiorleando commented on kubernetes/spring-microservice-deployment-gitlab-helm/README.md
> +To perform this step perfectly you need to create the variables `DOCKER_PASSWORD` and `DOCKER_LOGIN` in your project. These variables must contain the password and username of your docker hub account
To do this, go to settings > CI/CD then variables ---> To to this, from your GitLab project repository, go to `settings > CI/CD` then **variables** section. Do remember to set these as Protected since these are sensible.

2023-05-07 04:44 UTC, dassiorleando commented on kubernetes/spring-microservice-deployment-gitlab-helm/README.md
> +- **microservices-configuration** : this folder must be stored in another repository, it contains the configuration files of our different microservices such as :
How is the folder **microservices-configuration** being used within the setup? Also, can we move it to the root folder (spring-microservice-deployment-gitlab) of the project and update the article accordingly?

---------

Are you referring to the Spring application properties, if  Yes lest point it out. Thanks.

2023-05-07 04:44 UTC, dassiorleando commented on kubernetes/spring-microservice-deployment-gitlab-helm/README.md
> +![Capture](https://user-images.githubusercontent.com/70517765/229860467-6d2b6c34-4d90-4344-bbc3-96202044b04c.PNG)
Let's use local images instead or remote links, please.

Sample usages in this article: https://github.com/numerica-ideas/community/tree/master/aws/configure-aws-cli-multi-account-strategy

2023-05-07 04:44 UTC, dassiorleando commented on kubernetes/spring-microservice-deployment-gitlab-helm/README.md
> +Advantages of using Helm for deployment on a Kubernetes cluster:
Just to understand please, k8s doesn't do all of these points?

2023-05-07 04:44 UTC, dassiorleando commented on kubernetes/spring-microservice-deployment-gitlab-helm/README.md
> +- **kubernetes** : contains the different files to deploy our application on kubernetes without using Helm
This **kubernetes** folder has been removed from the project, right?
So I would recommend deleting this line as well.

2023-05-07 04:44 UTC, dassiorleando commented on kubernetes/spring-microservice-deployment-gitlab-helm/README.md
> +In conclusion, deploying **microservices** to a Kubernetes cluster with Helm via **GitLab CI** can be a powerful way to automate the building, testing, and deployment of your applications. With the u
The conclusion looks long to me, could we make a very simple version in one paragraph?

Maybe the following could help:

To sum up, we discussed the benefits of using Helm with Kubernetes to automate the deployment of microservices. It provides steps to set up a CI/CD pipeline using GitLab CI and Helm, allowing for efficient deployment of applications and increased productivity. By utilizing these technologies, developers can focus on coding, and automation can handle the rest, resulting in a reliable and scalable solution for deploying microservices in a modern software development environment.

2023-05-07 18:46 UTC, kemanedonfack commented on kubernetes/spring-microservice-deployment-gitlab-helm/.gitlab-ci.yml
> +    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
Provide a password using STDIN (--password-stdin)
To run the docker login command non-interactively, you can set the --password-stdin flag to provide a password through STDIN . Using STDIN prevents the password from ending up in the shell's history, or log-files.

2023-05-07 18:48 UTC, kemanedonfack commented on kubernetes/spring-microservice-deployment-gitlab-helm/README.md
> +To perform this step perfectly you need to create the variables `DOCKER_PASSWORD` and `DOCKER_LOGIN` in your project. These variables must contain the password and username of your docker hub account
Don't understand the issue

2023-05-07 19:38 UTC, kemanedonfack commented on kubernetes/spring-microservice-deployment-gitlab-helm/README.md
> +- **microservices-configuration** : this folder must be stored in another repository, it contains the configuration files of our different microservices such as :
it's not the application.properties file. But these configurations will complete our local configuration file

2023-05-07 20:22 UTC, kemanedonfack commented on kubernetes/spring-microservice-deployment-gitlab-helm/README.md
> +Advantages of using Helm for deployment on a Kubernetes cluster:
Not all. I'll remove those applicable to kubernetes and leave those specific to helm

2023-05-09 00:47 UTC, dassiorleando commented on kubernetes/spring-microservice-deployment-gitlab-helm/.gitlab-ci.yml
> +    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
Good stuff, Thanks for the clarification 👍

2023-05-09 00:49 UTC, dassiorleando commented on kubernetes/spring-microservice-deployment-gitlab-helm/README.md
> +To perform this step perfectly you need to create the variables `DOCKER_PASSWORD` and `DOCKER_LOGIN` in your project. These variables must contain the password and username of your docker hub account
It's about rephrasing your sentence the "--->" separate the actual and suggested change.

2023-05-09 00:50 UTC, dassiorleando commented on kubernetes/spring-microservice-deployment-gitlab-helm/README.md
> +- **microservices-configuration** : this folder must be stored in another repository, it contains the configuration files of our different microservices such as :
Ok got it, any chance we could centralize it into the same folder while still pointing out that it should be put somewhere else?

2023-05-09 00:51 UTC, dassiorleando commented on kubernetes/spring-microservice-deployment-gitlab-helm/README.md
> +Advantages of using Helm for deployment on a Kubernetes cluster:
That'll be great.

2023-05-09 08:50 UTC, kemanedonfack commented on kubernetes/spring-microservice-deployment-gitlab-helm/README.md
> +- **microservices-configuration** : this folder must be stored in another repository, it contains the configuration files of our different microservices such as :
currently the folder containing the configuration files is in the same folder as all the source code. And I mentioned in the article that it must be placed in another repository for everything to work properly

2023-05-09 09:05 UTC, kemanedonfack commented on kubernetes/spring-microservice-deployment-gitlab-helm/README.md
> +To perform this step perfectly you need to create the variables `DOCKER_PASSWORD` and `DOCKER_LOGIN` in your project. These variables must contain the password and username of your docker hub account
Will this one be okay?

To set up the required variables, navigate to the "Settings" tab in your GitLab project repository, then select "CI/CD" and go to the "Variables" section. Remember to mark the variables "DOCKER_PASSWORD" and "DOCKER_LOGIN" as "Protected" since they contain sensitive information.

2023-05-10 10:15 UTC, dassiorleando commented on kubernetes/spring-microservice-deployment-gitlab-helm/README.md
> +To perform this step perfectly you need to create the variables `DOCKER_PASSWORD` and `DOCKER_LOGIN` in your project. These variables must contain the password and username of your docker hub account
@kemanedonfack it looks GREAT than my previous suggestion, I like it.

2023-05-10 12:40 UTC, kemanedonfack commented
I'm going to close this PR and create a new one with all the changes.

2023-05-14 15:38 UTC, dassiorleando commented
@kemanedonfack let's not close it till it's merged please, we'll lose this review history by doing so ... only one PR should be created per writing.

Could you bring this back with the appropriate updates, please?

2023-05-14 15:59 UTC, kemanedonfack commented
@dassiorleando  all changes are available on my repository fork. i don't know how to merge

2023-05-21 23:28 UTC, merged

2023-05-22 00:34 UTC, dassiorleando commented
> @dassiorleando all changes are available on my repository fork. i don't know how to merge

I just merged it, Thanks for the hard work.