Auto Scaling Group on AWS with Terraform
numerica-ideas/community pull request #64
Opened 2023-06-11 22:46 UTC by kemanedonfack

2023-07-03 09:58 UTC, dassiorleando requested changes
@kemanedonfack in my opinion, that's an EXCELLENT article, well-detailed and oriented.

I let you some small comments to make it even better, I hope it could help somehow.

2023-07-03 09:58 UTC, dassiorleando commented on terraform/auto-scaling-group-on-aws-with-terraform/README.md
> +- **Scalability**: The Auto Scaling Group allows your infrastructure to scale up or down automatically based on demand. As traffic increases, the group adds more instances to handle the load, ensurin
**scale up or down: **

As of my knowledge, I don't think AWS offers a service to scale vertically (UP / DOWN), rather, ASG scales OUT and IN which we always refer to as **Horizontal Scaling**.

2023-07-03 09:58 UTC, dassiorleando commented on terraform/auto-scaling-group-on-aws-with-terraform/README.md
> +  map_public_ip_on_launch = "true" //it makes this a public subnet
According to the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet#map_public_ip_on_launch), the flag **"map_public_ip_on_launch"** indicates whether or not the instances launched into the subnet should be assigned a *public IP address*.

While a **"public subnet"** is a subnet associated with a Route Table with a route to an Internet gateway (IG).

Could you improve the 6 occurrences of this flag in the code and article?

2023-07-03 09:58 UTC, dassiorleando commented on terraform/auto-scaling-group-on-aws-with-terraform/README.md
> +resource "aws_subnet" "second_public_subnet" {
I would start with the "var.subnet_cidrs[0] & var.availability_zone[0]" for the first public subnet and end with "var.subnet_cidrs[1] & var.availability_zone[1]" for the second one so that the readers will have a better experience going through the material.

2023-07-03 09:58 UTC, dassiorleando commented on terraform/auto-scaling-group-on-aws-with-terraform/README.md
> +#It enables our vpc to connect to the internet
Still, to improve the reading experience, could you add a space before the comment text? Just right after the **#** sign.

Many occurrences exist.

2023-07-03 09:58 UTC, dassiorleando commented on terraform/auto-scaling-group-on-aws-with-terraform/README.md
> +  # dynamic block who create two rules to allow inbound traffic
Dynamic block "that creates"

2023-07-03 09:58 UTC, dassiorleando commented on terraform/auto-scaling-group-on-aws-with-terraform/security_group.tf
> +  # dynamic block who create two rules to allow inbound traffic
Dynamic block "that creates"

2023-07-03 09:58 UTC, dassiorleando commented on terraform/auto-scaling-group-on-aws-with-terraform/variables.tf
> +  default = "wordpressKey"
Could we rename the default EC2 key to something like: "ec2Key"?
Since the article has nothing to do with WordPress, it isn't that specific right?

2023-07-03 09:58 UTC, dassiorleando commented on terraform/auto-scaling-group-on-aws-with-terraform/README.md
> +- **aws_launch_template "instances_configuration"**: This resource defines a launch template that specifies the configuration for the EC2 instances launched by the Auto Scaling Group. It includes par
The Role section below is a duplicate of this paragraph, could we merge it while making sure the idea explained goes straight to the point? So that at the end we can only have a single paragraph for this bullet item.

2023-07-03 09:58 UTC, dassiorleando commented on terraform/auto-scaling-group-on-aws-with-terraform/README.md
> +- **aws_autoscaling_group "asg"**: This resource configures the Auto Scaling Group. It defines the group's name, minimum and maximum number of instances, desired capacity, health check settings, and
The Role section below is a duplicate of this paragraph, could we merge it while making sure the idea explained goes straight to the point? So that at the end we can only have a single paragraph for this bullet item.

2023-07-03 09:58 UTC, dassiorleando commented on terraform/auto-scaling-group-on-aws-with-terraform/README.md
> +- **aws_autoscaling_policy "avg_cpu_policy_greater"**: This resource creates an Auto Scaling policy that adjusts the capacity of the Auto Scaling Group based on CPU utilization. In this example, the
The Role section below is a duplicate of this paragraph, could we merge it while making sure the idea explained goes straight to the point? So that at the end we can only have a single paragraph for this bullet item.

2023-07-03 15:36 UTC, kemanedonfack commented on terraform/auto-scaling-group-on-aws-with-terraform/README.md
> +- **Scalability**: The Auto Scaling Group allows your infrastructure to scale up or down automatically based on demand. As traffic increases, the group adds more instances to handle the load, ensurin
Exactly

2023-07-03 16:22 UTC, kemanedonfack commented
I have made all changes

2023-07-04 12:20 UTC, dassiorleando commented
@kemanedonfack Excellent content, I approve it 💯 🥇

2023-07-04 12:21 UTC, dassiorleando approved these changes

2023-07-04 12:22 UTC, dassiorleando commented
I'll add some metadata to the article as well as link it to the main folder in the repository, the next time you could do the same if you don't mind.

2023-07-04 12:23 UTC, merged