Algorithm challenge: Combinations
numerica-ideas/community pull request #69
Opened 2023-07-05 14:21 UTC by noelfoka

## Algorithm challenge: Combinations

In this challenge, we wrote a function that:

- "combine" generates all possible combinations of numbers from 1 to n with length k.
- Uses a recursive helper function "x" to generate the combinations.

2023-07-06 11:29 UTC, messaismael requested changes
Highlight the name of the variables, functions name, and parameters that you mention in the description.

Egg: 
The function first checks if the input is valid (`n` must be greater than or equal to `k`, and `k` must be greater than or equal to `1`). If the input is invalid, an empty array is returned.

2023-07-06 11:29 UTC, messaismael commented on algorithms/combinations.md
> +The code provided below is a JavaScript implementation of the "combine" function, which generates all possible combinations of numbers from 1 to n with length k.
.., which return all possible combinations of `k` numbers chosen from the range `[1, n]` given two integers `n` and `k`, representing respectively the range of numbers and the length of the combinations..

2023-07-06 11:29 UTC, messaismael commented on algorithms/combinations.md
> +var x = function (result, y0, x0, n, k) {
The name of this function is not meaningful enough

2023-07-06 11:29 UTC, messaismael commented on algorithms/combinations.md
> +var x = function (result, y0, x0, n, k) {
The same comment regarding its parameters:  `y0`,  `x0`

2023-07-06 11:29 UTC, messaismael commented on algorithms/combinations.md
> +By Noel Foka
The link of your GitHub profile

2023-07-06 11:29 UTC, messaismael commented on algorithms/combinations.md
> + This is because the function takes two parameters, n and k, which represent the range of numbers and the length of the combinations, respectively. It returns an array of arrays, where each inner arr
You can remove this sentence

2023-07-06 20:36 UTC, messaismael approved these changes

2023-07-06 20:37 UTC, messaismael commented
@dassiorleando It's 🆗

2023-07-08 17:32 UTC, dassiorleando requested changes
@noelfoka could you please add the **Runtime** before your name at the end?

Example: https://github.com/numerica-ideas/community/blob/master/algorithms/maximum-subarray.md

2023-07-08 18:19 UTC, noelfoka commented
I think it's already good

2023-07-13 10:08 UTC, dassiorleando approved these changes

2023-07-13 10:09 UTC, merged

2023-07-13 10:12 UTC, dassiorleando commented
Great code change @noelfoka and Excellent review as usual @messaismael, I just approved it.

@messaismael do you see any possibilities of improvements for the guide that you wrote?
https://github.com/numerica-ideas/community/blob/master/algorithms/guide.md