Spring Boot Actuator
numerica-ideas/community pull request #75
Opened 2023-07-24 04:35 UTC by CedrickTAGNE

2023-07-27 16:01 UTC, dassiorleando commented on web/spring-boot-actuator/README.md
> +### Need more?
I see this section (Need more?) best positioned before the conclusion.

2023-07-27 16:02 UTC, dassiorleando commented on web/spring-boot-actuator/README.md
> +
Could we add the following before the conclusion?

The complete source code of the project is available on [GitHub](https://github.com/numerica-ideas/community/tree/master/web/spring-boot-actuator).

2023-07-27 16:15 UTC, dassiorleando commented on web/spring-boot-actuator/README.md
> +## Monitoring Application Metrics
There are a few repetitions in the overall article, in which concepts are defined/introduced multiple times, here's one as a reference:

<img width="1242" alt="Screenshot 2023-07-27 at 12 14 07" src="https://github.com/numerica-ideas/community/assets/7150752/d741e2f5-668f-48fa-b557-d5e6c01d88dd">

2023-07-27 16:24 UTC, dassiorleando commented on web/spring-boot-actuator/README.md
> +let's dive into the world of Spring Boot Actuator and unlock the enhanced monitoring and management capabilities it brings to the Spring Boot ecosystem.
I believe this sentence may not be necessary after what is said at the top, another duplicate.

2023-08-06 14:35 UTC, danielkaiser80 requested changes

2023-08-06 14:35 UTC, danielkaiser80 commented on web/.gitignore
Seems like this is coming from an old IDE... https://superuser.com/questions/1683234/what-are-metadata-directories-for
I would then add it to an ignore file on the local machine only, as not everyone uses the same IDEs

2023-08-06 14:35 UTC, danielkaiser80 commented on web/spring-boot-actuator/README.md
> +Spring Boot Actuator (V2.x) is a powerful toolset that provides extensive monitoring, management, and operational capabilities to Spring Boot applications. With Actuator, developers gain unparalleled
Maybe write a little short note on what an "actuator" actually is, neither I do like the word "toolset", maybe we find something better here.

2023-08-06 14:35 UTC, danielkaiser80 commented on web/spring-boot-actuator/README.md
> +- **Core Functionalities of spring Boot Actuator**
Spring should always start with capital letter.

2023-08-06 14:35 UTC, danielkaiser80 commented on web/spring-boot-actuator/README.md
> +Enabling Actuator in a Spring boot project is easy as adding a dependency to a project :). You can add it during the creation of you springBoot App or add it in an existing project Depending on wich
"is as easy as"

2023-08-06 14:35 UTC, danielkaiser80 commented on web/spring-boot-actuator/README.md
> +After doing this we will be able to see endpoints actually availlable throught: http://localhost:8080/actuator
I would not change from "you" to "we" but otherwise I like the sentence

2023-08-06 14:35 UTC, danielkaiser80 commented on web/spring-boot-actuator/README.md
> +#### Disable/Hide some actuators endpoints
"Disable or Hide Certain Actuator Endpoints." is even a bit better ;-)

2023-08-07 10:27 UTC, dassiorleando commented
@CedrickTAGNE is there anything new on this thread?

2023-08-09 13:29 UTC, CedrickTAGNE commented
@dassiorleando  yes, I'm applying changes you and @danielkaiser80 left.

2023-09-03 02:22 UTC, dassiorleando commented on web/.gitignore
> Seems like this is coming from an old IDE... https://superuser.com/questions/1683234/what-are-metadata-directories-for I would then add it to an ignore file on the local machine only, as not everyone uses the same IDEs

it's a **".gitignore"** file, not a .metadata one, but thanks for the info.

Its presence is correct but I expected it to be included in the article folder, not outside.

CC: @CedrickTAGNE

2023-09-03 02:29 UTC, dassiorleando commented on web/spring-boot-actuator/README.md
> +After doing this we will be able to see endpoints actually availlable throught: http://localhost:8080/actuator
@danielkaiser80 you are correct, it's better to keep using the "you" form only, Thanks.

2023-09-03 02:41 UTC, dassiorleando commented on web/spring-boot-actuator/README.md
> +Spring Boot Actuator (V2.x) is a powerful toolset that provides extensive monitoring, management, and operational capabilities to Spring Boot applications. With Actuator, developers gain unparalleled
I myself don't know what could fit either than toolset, if you guys find something, we can update the article anytime.

2023-09-03 02:43 UTC, dassiorleando approved these changes
@CedrickTAGNE everything looks great for my eyes, Thank you for this nice article 🚀 

Thank you for your review too @danielkaiser80 👍

2023-09-03 03:31 UTC, dassiorleando approved these changes
@CedrickTAGNE the article is DONE, but only a few metadata are necessary to move live with it.

By doing it myself you wouldn't know what to do for the future articles, so I just documented these all here first ... I'll summarize the articles hints into a guide very soon or later.

2023-09-03 03:31 UTC, dassiorleando commented on web/spring-boot-actuator/README.md
> +## Conclusion
Before the conclusion, could you write this?

———————

We have just started our journey to build a network of professionals to grow even more our free knowledge-sharing community that’ll give you a chance to learn interesting things about topics like cloud computing, software development, and software architectures while keeping the door open to more opportunities.

Does this speak to you? If **YES**, feel free to [Join our Discord Server](https://discord.numericaideas.com) to stay in touch with the community and be part of independently organized events.

———————

Here's an example in another article: https://github.com/numerica-ideas/community/tree/master/aws/cd-springboot-aws-eb-github-actions#conclusion

2023-09-03 03:31 UTC, dassiorleando commented on web/spring-boot-actuator/README.md
> +
After the conclusion, could you write this?

Thanks for reading this article. Like, recommend, and share if you enjoyed it. Follow us on [Facebook](https://www.facebook.com/numericaideas), [Twitter](https://twitter.com/numericaideas), and [LinkedIn](https://www.linkedin.com/company/numericaideas) for more content.

Here's an example in another article: https://github.com/numerica-ideas/community/tree/master/aws/cd-springboot-aws-eb-github-actions#conclusion

2023-09-03 03:31 UTC, dassiorleando commented on web/spring-boot-actuator/README.md
> +## Introduction
Before the introduction, could you add this?

**This article was originally written by "Cedrick Tagne" on the blog**: https://blog.numericaideas.com/spring-boot-actuator

Sample: https://github.com/numerica-ideas/community/tree/master/aws/cd-springboot-aws-eb-github-actions#continuous-deployment-of-spring-boot-to-aws-elastic-beanstalk-via-github-actions-a-step-by-step-guide

2023-09-03 03:31 UTC, dassiorleando commented on web/spring-boot-actuator/README.md
> +# Spring Boot Production-Ready: Enhanced Monitoring and Management using Actuator
On the same line as the article title, could you add this hit icon?

The whole line will be:

# Spring Boot Production-Ready: Enhanced Monitoring and Management using Actuator&nbsp;[![Hits](https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fgithub.com%2Fnumerica-ideas%2Fcommunity%2Ftree%2Fmaster%2Fweb%2Fspring-boot-actuator&count_bg=%2379C83D&title_bg=%23555555&icon=&icon_color=%23E7E7E7&title=hits&edge_flat=false)](https://blog.numericaideas.com/spring-boot-actuator)

2023-09-03 03:31 UTC, dassiorleando commented on web/spring-boot-actuator/README.md
> +## Core Functionalities of Spring Boot Actuator
Before the Core functionalities, here's a suggestion of the article featured image to use (feel free to suggest any change or something else).

Please, use the compressed (not altered) image version to add to the **images** folder.

![Spring Boot Actuator](https://github.com/numerica-ideas/community/assets/7150752/acdb4860-680f-4e8c-8e50-bf75dea21497)

Compressed featured image: 
[Spring-Boot-Actuator-Image.zip](https://github.com/numerica-ideas/community/files/12505142/Spring-Boot-Actuator-Image.zip)


Sample from another article: https://github.com/numerica-ideas/community/tree/master/aws/configure-aws-cli-multi-account-strategy#introduction

2023-09-03 04:10 UTC, CedrickTAGNE commented on web/.gitignore
I added it in the .ignore of web folder

2023-09-03 21:31 UTC, danielkaiser80 approved these changes
I would still love when this web/.gitignore file were removed, as it could be distracting, as most people will think: what is this even about...
Still, this is not a big issue I think, so I'll also approve.

2023-09-03 21:50 UTC, danielkaiser80 commented on web/spring-boot-actuator/README.md
> +Spring Boot Actuator (V2.x) is a powerful toolset that provides extensive monitoring, management, and operational capabilities to Spring Boot applications. With Actuator, developers gain unparalleled
ChatGPT told me that toolset would be very appropriate, just asked it ;-)

2023-09-04 13:45 UTC, dassiorleando commented
> I would still love when this web/.gitignore file were removed, as it could be distracting, as most people will think: what is this even about... Still, this is not a big issue I think, so I'll also approve.

I agree with you, could you please remove it @CedrickTAGNE?

Maybe adding its content into the existing global **".gitignore"** at the root of the repository?

2023-09-06 11:41 UTC, merged

2023-09-06 11:42 UTC, dassiorleando commented
@CedrickTAGNE it's merged by now, we'll plan to publish it as soon as possible this week.
Great content, Thank you