AWS scale wordpress with terraform
numerica-ideas/community pull request #77
Opened 2023-07-25 17:52 UTC by kemanedonfack

2023-07-28 18:59 UTC, dassiorleando requested changes
Great article/project, could you please improve or clarify the comments I just left on the top?
I'm impatient to see it live, Thanks for that @kemanedonfack

2023-07-28 18:59 UTC, dassiorleando commented on terraform/aws-scale-wordpress/README.md
> +- Familiarity with `WordPress` and its deployment on AWS, as discussed in our previous article.
I do believe it's a good idea to add the previous article as the lat point of the prerequisite.

Something like

- Read the previous article: [Deploying WordPress on a 2-Tier AWS Architecture with Terraform](https://blog.numericaideas.com/deploy-wordpress-2-tier-aws-architecture-with-terraform)

2023-07-28 18:59 UTC, dassiorleando commented on terraform/aws-scale-wordpress/README.md
> +If you would like to delve deeper into the concept of Auto Scaling Group and its benefits, I have a dedicated article that covers it in detail. It provides valuable insights into how ASG works, and i
It's recommended not to use the "I" pronoun for such, instead: ... **we have a dedicated article** ...

2023-07-28 18:59 UTC, dassiorleando commented on terraform/aws-scale-wordpress/README.md
> +In the `main.tf` file, we need to remove our 2 aws_instance resources and add some new resources : **aws_launch_template** to define the configuration for our EC2 instances The template specifies the
instances, the template specifies the AMI ...

2023-07-28 18:59 UTC, dassiorleando commented on terraform/aws-scale-wordpress/README.md
> +resource "aws_lb" "alb" {
I don't get how you linked the ALB and ASG in this section, while this section description implies it.

2023-07-28 18:59 UTC, dassiorleando commented on terraform/aws-scale-wordpress/README.md
> +    aws_efs_mount_target.efs_mount_target_1,
According to AWS, a highly available deployment should be done in at least three (3) AZs.

So we may need to have 3 subnets and 3 EFS mount points as per my understanding, please do confirm if I'm wrong.

2023-07-28 18:59 UTC, dassiorleando commented on terraform/aws-scale-wordpress/README.md
> +resource "aws_launch_template" "instances_configuration" {
Why don't we provide the installation script as user_data to the launch template instead of performing remote execution?

Like so: user_data = filebase64("install_script.sh")

2023-07-28 18:59 UTC, dassiorleando commented on terraform/aws-scale-wordpress/README.md
> +        Resource = "*"
Should this be on a specific bucket or for every **resource**?

By applying the least privilege we should create the S3 bucket + distribution first, then using them for the IAM policy/role.

2023-07-29 12:18 UTC, kemanedonfack commented on terraform/aws-scale-wordpress/README.md
> +    aws_efs_mount_target.efs_mount_target_1,
Ok I add a new AZ

2023-07-29 20:13 UTC, kemanedonfack commented
@dassiorleando Everything is okay. I'm working on a new architectural diagram

2023-07-29 20:30 UTC, dassiorleando commented
@kemanedonfack but I don't see your last commit, and looks like you had trouble merging upstream changes.
Could you take another look?

The PR/branch state isn't clean.

https://github.com/numerica-ideas/community/pull/77/commits

2023-07-29 21:49 UTC, kemanedonfack commented
I have had an issue but now it's okay

2023-08-07 10:25 UTC, dassiorleando requested changes
@kemanedonfack The technical part is great as before, just some points that came back and the article structure/experience to improve.

2023-08-07 10:25 UTC, dassiorleando commented on terraform/aws-scale-wordpress/README.md
> +In this section, I will explain the modifications made to the existing Terraform files to incorporate ASG into our WordPress deployment.
I still see a lot of **"I will"** within the article, close to 10 occurrences.
Let's replace it with **"we will"** or **"we'll"**.

2023-08-07 10:25 UTC, dassiorleando commented on terraform/aws-scale-wordpress/README.md
> +# AWS Scale WordpPress
@kemanedonfack The article doesn't cover the structure we established earlier to better the reading experience.

Right now, I don't know why we are creating an S3 bucket, it's at the very end of the article that we have that reason, which could be better to give more details first.

What is this article about? WordPress Scalability, right?
- So let's emphasize the possibilities (the solutions aspect isn't clearly defined) before jumping on the technicalities (exceptionally done).
- All the technical changes are great, just that it's not smooth enough for someone who wants to scale his WP deployment on AWS. Why are we using ASG? Why S3?

Maybe creating a section before the **Prerequisites** could solve that smoothness? Something titled **"Solutions Architecture"**, in which we can explain the choices first, I mean the Scalability Possibilities, each of them being a sub-menu item:

## Solutions Architecture
     ### - Read Replicas
     ### - Auto Scaling Group
     ### - Cache and serve web assets using S3 and CloudFront
     ### - The importance of EFS

<img width="602" alt="Screenshot 2023-08-07 at 06 13 36" src="https://github.com/numerica-ideas/community/assets/7150752/c0f6a9c6-3d6b-4b48-b354-530b89956399">

**Note**: let's ensure the implementation part, down to the prerequisites, doesn't duplicate the description provided on the top.

2023-08-07 10:25 UTC, dassiorleando commented on terraform/aws-scale-wordpress/README.md
> +        Resource = "*"
This point is still valid, the permission is too wide, while we can stick only to listing the **bucket (var.bucket_name)** that we created for the WP deployment, and it appears to be done just down ... so it's also a duplicate statement.

2023-08-07 10:25 UTC, dassiorleando commented on terraform/aws-scale-wordpress/README.md
> +![architecture diagram](./images/Deploy%20WordPress%20on%20a%202-Tier%20AWS%20Architecture%20with%20Terraform.png)
Is there any chance to improve the Architecture Diagram by adding the third AZ and making it easier to read?

2023-08-07 10:47 UTC, kemanedonfack commented on terraform/aws-scale-wordpress/README.md
> +        Resource = "*"
I have already solved this and pushed the code

2023-08-09 08:40 UTC, kemanedonfack commented
@dassiorleando I'm done

2023-08-24 11:17 UTC, dassiorleando requested changes
The diagram doesn’t reflect the fact that all the instances hit the same master RDS.

Maybe we should remove the read replica from the equation since it’s not forcibly a read-heavy system (reporting …). If you even use it, some instances won’t be able to perform CRUD operations as they’ll be read only.

I don’t see where it’s helpful to keep it, if each instance get started with the master RDS, then all instances hit the same DB and the diagram and code should reflect it.

2023-09-10 11:52 UTC, dassiorleando requested changes
@kemanedonfack  great change, Let's bring back two things please:
- Featured image
- Read replicas section

2023-09-10 11:52 UTC, dassiorleando commented on terraform/aws-scale-wordpress/README.md
> -### Read Replicas for RDS
@kemanedonfack please, could you please keep this section in the article? It remains a great point for database scalability.
I don't think the intent was to delete it.

2023-09-10 11:52 UTC, dassiorleando commented on terraform/aws-scale-wordpress/README.md
> +  username                = var.db_user
Great change, could we come back to the old version of the featured image?

I made a mistake asking you to change it, sorry for that ... I gave it more attention and I noticed it was 100% correct.

Here's the [link](https://raw.githubusercontent.com/numerica-ideas/community/7341bce3ec12383b3ff9fa03f686fc292faf9da6/terraform/aws-scale-wordpress/images/AWS%20Scale%20WordPress%20on%20a%202-Tier%20AWS%20Architecture%20with%20Terraform.png) to the old version to use.

Just some arrows to put before the icons/texts:
<img width="1298" alt="Screenshot 2023-09-10 at 07 48 26" src="https://github.com/numerica-ideas/community/assets/7150752/8bd646d7-58df-46a5-9a19-c9899b051d53">

Thank you

2023-09-10 13:02 UTC, kemanedonfack commented
@dassiorleando I'm done

2023-09-10 13:16 UTC, merged