Apply SOLID Principles in a Real Angular Project
numerica-ideas/community pull request #99
Opened 2023-08-24 20:26 UTC by DDarkBC

This article is for Angular Developers willing to apply SOLID Principles in their Angular Projects.

2023-08-31 21:13 UTC, dassiorleando requested changes
@DDarkBC great technical tips in regard to the SOLID principles.
We may want Romuald to produce the PDF version according to Ni's design.

But as soon as you make the requested changes, I could approve it.

Thanks for all the efforts.

2023-08-31 21:13 UTC, dassiorleando commented on web/solid-principles-in-angular-project/README.md
> +---
Please, could you update the article to match the one on the ["Git Cheat Sheet"](https://github.com/numerica-ideas/community/blob/master/cheatsheets/git/README.md)?

It's OK to duplicate the cta image to your images folder.

........................................................................................................................................

![GitCheatSheetCTA](./cta.png)

———————

We have just started our journey to build a network of professionals to grow even more our free knowledge-sharing community that’ll give you a chance to learn interesting things about topics like cloud computing, software development, and software architectures while keeping the door open to more opportunities.

Does this speak to you? If **YES**, feel free to [Join our Discord Server](https://discord.numericaideas.com) to stay in touch with the community and be part of independently organized events.

———————

Thanks for reading this article. Like, recommend, and share if you enjoyed it. Follow us on [Facebook](https://www.facebook.com/numericaideas), [Twitter](https://twitter.com/numericaideas), and [LinkedIn](https://www.linkedin.com/company/numericaideas) for more content.

2023-08-31 21:13 UTC, dassiorleando commented on web/solid-principles-in-angular-project/README.md
> +
Just down to the article name could you add this?

............................................................

This document was originally written by "Chris Kouakam" on the blog: https://blog.numericaideas.com/solid-principles-in-angular

2023-08-31 21:13 UTC, dassiorleando commented on web/solid-principles-in-angular-project/README.md
> +
@DDarkBC please, could you move it to the **cheatsheets** folder instead?
It's a great summary to be shared as a cheat sheet for maximum engagement.

**web ---> cheatsheets**

I'll ping Romuald to see if he could produce the PDF version with respect to our design template that he built.
Sample: https://github.com/numerica-ideas/community/blob/master/cheatsheets/git/git-cheat-sheet.pdf

2023-08-31 21:23 UTC, dassiorleando commented on web/solid-principles-in-angular-project/README.md
> +![Single Responsibility Principle (SRP)](SRP.png)
Les images ne sont pas bien référencées.

Les paths doivent être sur la forme **"./images/xxxxx.png"**

2023-09-02 10:53 UTC, dassiorleando commented on web/solid-principles-in-angular-project/README.md
> +---
@DDarkBC what you have done down the content is slightly different than the ones of the Git cheat sheet.

https://raw.githubusercontent.com/numerica-ideas/community/master/cheatsheets/git/README.md

2023-09-02 10:54 UTC, dassiorleando commented on web/solid-principles-in-angular-project/README.md
> +
This should be done at the top of the article, not down.

E.g.: https://raw.githubusercontent.com/numerica-ideas/community/master/cheatsheets/git/README.md

2023-09-02 10:57 UTC, dassiorleando commented on web/solid-principles-in-angular-project/README.md
> +
I believe that the folder would be more simple without the "-project" suffix.

**solid-principles-in-angular** instead of ~~solid-principles-in-angular-project~~.

2023-09-02 10:59 UTC, dassiorleando requested changes
@DDarkBC Thanks for the changes, what do you think about changing more stuff to better align it to the other cheat sheet?

Here's the other one that I'm taking as an example:
https://raw.githubusercontent.com/numerica-ideas/community/master/cheatsheets/git/README.md

2023-09-02 11:16 UTC, DDarkBC commented on web/solid-principles-in-angular-project/README.md
> +---
Yeah that's true. I fixed them all.

2023-09-02 11:24 UTC, merged

2023-09-02 11:25 UTC, dassiorleando commented
Great changes, I just merged it @DDarkBC